In [184]:
# print(len(g)) #x
# print(len(g[0])) #y

4
5


In [1]:
import numpy as np
from collections import deque as Q

# direction vectors
dx = [-1, 1, 0, 0, -1, -1, 1, 1]
dy = [0, 0, -1, 1, -1, 1, -1, 1]

# function for cell if a cell visited or not
def isValid(vis, x,y, grid):
    
    #if cell lies out of bounds
    if(x<0 or y<0 or x>=len(grid) or y>=len(grid[0])):
        return False
    
    # if cell is already visited
    if(vis[x][y]):
        return False
    
    return True


def bfs(grid, vis, x_, y_):
    q = Q()
    
    q.append((x_, y_))
    vis[x_][y_] = True
    
    while (len(q)>0):
        cell = q.popleft()
        x,y = cell[0],cell[1]
        print(grid[x][y], end=" ")
        
        for i in range(len(dx)):
            adj_x = x + dx[i]
            adj_y = y + dy[i]
            
            if (isValid(vis, adj_x, adj_y, grid)):
                q.append((adj_x, adj_y))
                vis[adj_x][adj_y] = True

vis = [[False for i in range(4)] for i in range(4)]

grid = []
k = 0
grid = []
for i in range(4):
    j_load = []
    for j in range(4):
        j_load.append(k)
        k+=1
    grid.append(j_load)
grid = np.array(grid)
vis = np.array(vis)

bfs(grid, vis, 0,0)

0 4 1 5 8 9 2 6 10 12 13 14 3 7 11 15 

In [2]:
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [3]:
import numpy as np
from collections import deque as Q

# direction vectors
dx = [-1, 1, 0, 0, -1, -1, 1, 1]
dy = [0, 0, -1, 1, -1, 1, -1, 1]

# function for cell if a cell visited or not
def isValid(vis, x,y, grid):
    
    #if cell lies out of bounds
    if(x<0 or y<0 or x>=len(grid) or y>=len(grid[0])):
        return False
    
    # if cell is already visited
    if(vis[x][y]):
        return False
    
    return True


def bfs(grid, vis, x_, y_):
    q = Q()
    
    q.append((x_, y_))
    vis[x_][y_] = True
    
    while (len(q)>0):
        cell = q.popleft()
        x,y = cell[0],cell[1]
        print(grid[x][y], end=" ")
        
        for i in range(len(dx)-4):
            adj_x = x + dx[i]
            adj_y = y + dy[i]
            
            if (isValid(vis, adj_x, adj_y, grid)):
                q.append((adj_x, adj_y))
                vis[adj_x][adj_y] = True

vis = [[False for i in range(4)] for i in range(4)]

grid = []
k = 0
grid = []
for i in range(4):
    j_load = []
    for j in range(4):
        j_load.append(k)
        k+=1
    grid.append(j_load)
grid = np.array(grid)
vis = np.array(vis)

bfs(grid, vis, 0,0)

0 4 1 8 5 2 12 9 6 3 13 10 7 14 11 15 

In [4]:
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [11]:
import numpy as np
from collections import deque as Q

# direction vectors
dx = [-1, 1, 0, 0, -1, -1, 1, 1]
dy = [0, 0, -1, 1, -1, 1, -1, 1]

# function for cell if a cell visited or not
def isValid(vis, x,y, grid):
    
    #if cell lies out of bounds
    if(x<0 or y<0 or x>=len(grid) or y>=len(grid[0]) or grid[x][y]!=0):
        return False
    
    # if cell is already visited
    if(vis[x][y]):
        return False
    
    return True


def bfs(grid, vis, x_, y_):
    q = Q()
    
    q.append((x_, y_))
    vis[x_][y_] = True
    
    while (len(q)>0):
        cell = q.popleft()
        x,y = cell[0],cell[1]
        print((x,y), end=" ")
        
        for i in range(len(dx)-4):
            adj_x = x + dx[i]
            adj_y = y + dy[i]
            
            if (isValid(vis, adj_x, adj_y, grid)):
                
                q.append((adj_x, adj_y))
                vis[adj_x][adj_y] = True

vis = [[False for i in range(4)] for i in range(4)]

grid = [[0,0,0,0],
       [0,0,1,0],
       [0,0,1,0],
       [0,0,0,0]]
grid = np.array(grid)
vis = np.array(vis)

bfs(grid, vis, 0,0)

(0, 0) (1, 0) (0, 1) (2, 0) (1, 1) (0, 2) (3, 0) (2, 1) (0, 3) (3, 1) (1, 3) (3, 2) (2, 3) (3, 3) 

In [12]:
grid

array([[0, 0, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 0]])

In [217]:
import queue


def createMaze():
    maze = []
    maze.append(["#","#", "#", "#", "#", "O","#"])
    maze.append(["#"," ", " ", " ", "#", " ","#"])
    maze.append(["#"," ", "#", " ", "#", " ","#"])
    maze.append(["#"," ", "#", " ", " ", " ","#"])
    maze.append(["#"," ", "#", "#", "#", " ","#"])
    maze.append(["#"," ", " ", " ", "#", " ","#"])
    maze.append(["#","#", "#", "#", "#", "X","#"])

    return maze

def createMaze2():
    maze = []
    maze.append(["#","#", "#", "#", "#", "O", "#", "#", "#"])
    maze.append(["#"," ", " ", " ", " ", " ", " ", " ", "#"])
    maze.append(["#"," ", "#", "#", " ", "#", "#", " ", "#"])
    maze.append(["#"," ", "#", " ", " ", " ", "#", " ", "#"])
    maze.append(["#"," ", "#", " ", "#", " ", "#", " ", "#"])
    maze.append(["#"," ", "#", " ", "#", " ", "#", " ", "#"])
    maze.append(["#"," ", "#", " ", "#", " ", "#", "#", "#"])
    maze.append(["#"," ", " ", " ", " ", " ", " ", " ", "#"])
    maze.append(["#","#", "#", "#", "#", "#", "#", "X", "#"])

    return maze


def printMaze(maze, path=""):
    for x, pos in enumerate(maze[0]):
        if pos == "O":
            start = x

    i = start
    j = 0
    pos = set()
    for move in path:
        if move == "L":
            i -= 1

        elif move == "R":
            i += 1

        elif move == "U":
            j -= 1

        elif move == "D":
            j += 1
        pos.add((j, i))
    
    for j, row in enumerate(maze):
        for i, col in enumerate(row):
            if (j, i) in pos:
                print("+ ", end="")
            else:
                print(col + " ", end="")
        print()
        


def valid(maze, moves):
    for x, pos in enumerate(maze[0]):
        if pos == "O":
            start = x

    i = start
    j = 0
    for move in moves:
        if move == "L":
            i -= 1

        elif move == "R":
            i += 1

        elif move == "U":
            j -= 1

        elif move == "D":
            j += 1

        if not(0 <= i < len(maze[0]) and 0 <= j < len(maze)):
            return False
        elif (maze[j][i] == "#"):
            return False

    return True


def findEnd(maze, moves):
    for x, pos in enumerate(maze[0]):
        if pos == "O":
            start = x

    i = start
    j = 0
    for move in moves:
        if move == "L":
            i -= 1

        elif move == "R":
            i += 1

        elif move == "U":
            j -= 1

        elif move == "D":
            j += 1

    if maze[j][i] == "X":
        print("Found: " + moves)
        printMaze(maze, moves)
        return True

    return False


# MAIN ALGORITHM

nums = queue.Queue()
nums.put("")
add = ""
maze  = createMaze2()

while not findEnd(maze, add): 
    add = nums.get()
    #print(add)
    for j in ["L", "R", "U", "D"]:
        put = add + j
        if valid(maze, put):
            nums.put(put)


Found: DLDDRDDDDRRD
# # # # # O # # # 
#       + +     # 
#   # # + # #   # 
#   #   + + #   # 
#   #   # + #   # 
#   #   # + #   # 
#   #   # + # # # 
#         + + + # 
# # # # # # # + # 
