In [2]:
import numpy as np
import warnings
warnings.filterwarnings('ignore')
import tensorflow as tf
from tensorflow.keras import datasets, layers, models
from tensorflow.keras.layers import Dense, Dropout, Flatten, Conv2D, MaxPooling2D
tf.__version__

'2.8.0'

In [2]:
a = np.array(np.random.randint(10))

In [3]:
a

array(6)

In [4]:
np.random.randint(1,10)

9

In [5]:
np.eye(5000,5000)

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [6]:
np.random.random((5))

array([0.00871851, 0.34147093, 0.33737929, 0.95904576, 0.19182944])

In [7]:
np.empty((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [8]:
a = np.array(np.random.random((3,2)))
b = np.array(np.random.random((1,2)))

In [9]:
np.dot(a,b.T)

array([[0.52743566],
       [0.00375175],
       [0.19339318]])

In [10]:
 np.std(a) 

0.3949987783927168

In [13]:
# !pip install --upgrade pip

In [12]:
# !pip install tensorflow

'2.8.0'

In [14]:
mnist = datasets.mnist

In [15]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train/255.0, x_test/255.0

11501568/11490434 [==============================] - 8s 1us/step


In [17]:
model = models.Sequential([Flatten(input_shape=(28,28)),
                           Dense(1024, activation=tf.nn.leaky_relu),
                           Dropout(0.3),
                           Dense(512, activation=tf.nn.leaky_relu),
                           Dropout(0.2),
                           Dense(10, activation=tf.nn.softmax)])

In [18]:
model.compile(optimizer="adam",
              loss="sparse_categorical_crossentropy",
              metrics=["accuracy"])

In [19]:
model.fit(x_train, y_train, epochs=5)

2022-04-08 23:21:00.473854: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 188160000 exceeds 10% of free system memory.
2022-04-08 23:21:00.802514: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 188160000 exceeds 10% of free system memory.


Epoch 1/5
1875/1875 [==============================] - 21s 2ms/step - loss: 0.2467 - accuracy: 0.9254
Epoch 2/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1588 - accuracy: 0.9535
Epoch 3/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1399 - accuracy: 0.9600
Epoch 4/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1304 - accuracy: 0.9640
Epoch 5/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1262 - accuracy: 0.9644


In [20]:
model.evaluate(x_test, y_test)

2022-04-08 23:21:38.092453: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 31360000 exceeds 10% of free system memory.
2022-04-08 23:21:38.135414: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 31360000 exceeds 10% of free system memory.


313/313 [==============================] - 1s 1ms/step - loss: 0.1150 - accuracy: 0.9718


[0.11502323299646378, 0.9718000292778015]

In [21]:
ip = tf.keras.Input(shape=(28,28))

In [22]:
x = Flatten()(ip)
x = Dense(1024, activation=tf.nn.leaky_relu)(x)
x = Dropout(0.3)(x)
x = Dense(512, activation=tf.nn.leaky_relu)(x)
x = Dropout(0.2)(x)
x = Dense(10, activation=tf.nn.softmax)(x)

In [23]:
model = tf.keras.models.Model(inputs=ip, outputs=x)

In [24]:
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 28, 28)]          0         
                                                                 
 flatten_2 (Flatten)         (None, 784)               0         
                                                                 
 dense_6 (Dense)             (None, 1024)              803840    
                                                                 
 dropout_4 (Dropout)         (None, 1024)              0         
                                                                 
 dense_7 (Dense)             (None, 512)               524800    
                                                                 
 dropout_5 (Dropout)         (None, 512)               0         
                                                                 
 dense_8 (Dense)             (None, 10)                5130  

In [25]:
model.compile(optimizer="adam",
              loss="sparse_categorical_crossentropy",
              metrics=["accuracy"])

In [26]:
model.fit(x_train, y_train, epochs=50)

Epoch 1/50


2022-04-08 23:21:49.700303: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 188160000 exceeds 10% of free system memory.


1875/1875 [==============================] - 3s 2ms/step - loss: 0.2511 - accuracy: 0.9233
Epoch 2/50
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1587 - accuracy: 0.9531
Epoch 3/50
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1401 - accuracy: 0.9597
Epoch 4/50
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1307 - accuracy: 0.9636
Epoch 5/50
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1262 - accuracy: 0.9658
Epoch 6/50
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1181 - accuracy: 0.9684
Epoch 7/50
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1165 - accuracy: 0.9690
Epoch 8/50
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1137 - accuracy: 0.9704
Epoch 9/50
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1140 - accuracy: 0.9708
Epoch 10/50
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1118 - accurac

In [70]:
import cv2

In [74]:
for i in range(0,10):
    cv2.imshow("imu", x_train[i])
    cv2.waitKey(0)
cv2.destroyAllWindows()

In [76]:
len(x_train[0])

28

In [82]:
model = tf.keras.applications.MobileNetV2(input_shape=((32,32,3)),
                                          include_top=False,
                                          weights="imagenet",
                                          pooling="avg")


9420800/9406464 [==============================] - 4s 0us/step


In [28]:
model = models.Sequential([Conv2D(28,(3,3), activation=tf.nn.leaky_relu, input_shape=(28,28,1)),
                           MaxPooling2D((2,2)),
                           Conv2D(56,(3,3), activation=tf.nn.leaky_relu),
                           MaxPooling2D((2,2)),
                           Conv2D(112,(3,3), activation=tf.nn.leaky_relu),
                           Flatten(),
                           Dense(1024, activation=tf.nn.leaky_relu),
                           Dropout(0.3),
                           Dense(512, activation=tf.nn.leaky_relu),
                           Dropout(0.2),
                           Dense(10, activation=tf.nn.softmax)])

In [29]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 26, 26, 28)        280       
                                                                 
 max_pooling2d (MaxPooling2D  (None, 13, 13, 28)       0         
 )                                                               
                                                                 
 conv2d_1 (Conv2D)           (None, 11, 11, 56)        14168     
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 5, 5, 56)         0         
 2D)                                                             
                                                                 
 conv2d_2 (Conv2D)           (None, 3, 3, 112)         56560     
                                                                 
 flatten_3 (Flatten)         (None, 1008)             

In [30]:
model.compile(optimizer="adam",
              loss="sparse_categorical_crossentropy",
              metrics=["accuracy"])

In [31]:
his = model.fit(x_train, y_train, epochs=10, validation_data=(x_test, y_test))

Epoch 1/10


2022-04-08 23:32:10.841851: I tensorflow/stream_executor/cuda/cuda_dnn.cc:368] Loaded cuDNN version 8201


1875/1875 [==============================] - 69s 26ms/step - loss: 0.1232 - accuracy: 0.9623 - val_loss: 0.0461 - val_accuracy: 0.9858
Epoch 2/10
1875/1875 [==============================] - 48s 26ms/step - loss: 0.0571 - accuracy: 0.9831 - val_loss: 0.0434 - val_accuracy: 0.9870
Epoch 3/10
1875/1875 [==============================] - 48s 26ms/step - loss: 0.0461 - accuracy: 0.9855 - val_loss: 0.0376 - val_accuracy: 0.9882
Epoch 4/10
1875/1875 [==============================] - 50s 27ms/step - loss: 0.0409 - accuracy: 0.9880 - val_loss: 0.0593 - val_accuracy: 0.9823
Epoch 5/10
1875/1875 [==============================] - 52s 28ms/step - loss: 0.0394 - accuracy: 0.9884 - val_loss: 0.0481 - val_accuracy: 0.9861
Epoch 6/10
1875/1875 [==============================] - 51s 27ms/step - loss: 0.0345 - accuracy: 0.9899 - val_loss: 0.0420 - val_accuracy: 0.9898
Epoch 7/10
1875/1875 [==============================] - 51s 27ms/step - loss: 0.0316 - accuracy: 0.9911 - val_loss: 0.0545 - val_accura

In [32]:
x_train.shape

(60000, 28, 28)

In [33]:
y_train.shape

(60000,)

In [34]:
x_test.shape

(10000, 28, 28)

In [35]:
y_test.shape

(10000,)

In [4]:
mnist = datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train/255.0, x_test/255.0

# expand new axis, channel axis 
x_train = np.expand_dims(x_train, axis=-1)
print(x_train.shape)

# [optional]: we may need 3 channel (instead of 1)
x_train = np.repeat(x_train, 3, axis=-1)
print(x_train.shape)

x_train = tf.image.resize(x_train, [32,32]) # if we want to resize
print(x_train.shape)

y_train = tf.keras.utils.to_categorical(y_train, num_classes=10)
print(x_train.shape, y_train.shape)

(60000, 28, 28, 1)
(60000, 28, 28, 3)


2022-04-08 23:44:53.217628: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero


(60000, 32, 32, 3)
(60000, 32, 32, 3) (60000, 10)


2022-04-08 23:44:54.047230: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-04-08 23:44:54.047696: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-04-08 23:44:54.068689: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-04-08 23:44:54.109438: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zer

In [5]:
ip = tf.keras.Input(shape=(32,32,3))
net = tf.keras.applications.ResNet50(input_tensor = ip,
                                          include_top=False,
                                          weights='imagenet')
gap = tf.keras.layers.GlobalAveragePooling2D()(net.output)
op = Dense(10, activation=tf.nn.softmax, use_bias=True)(gap)



94781440/94765736 [==============================] - 41s 0us/step


In [6]:
model = tf.keras.models.Model(inputs=net.input, outputs=op)

In [7]:
model.compile(optimizer="adam",
              loss=tf.keras.losses.CategoricalCrossentropy(),
              metrics=["accuracy"])

In [8]:
his = model.fit(x_train, y_train, epochs=1, batch_size=128)

2022-04-08 23:45:57.662777: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 737280000 exceeds 10% of free system memory.
2022-04-08 23:46:03.401349: I tensorflow/stream_executor/cuda/cuda_dnn.cc:368] Loaded cuDNN version 8201


469/469 [==============================] - 464s 944ms/step - loss: 0.1244 - accuracy: 0.9669


In [9]:
ip = tf.keras.Input(shape=(32,32,3))
net = tf.keras.applications.MobileNetV2(input_tensor = ip,
                                          include_top=False,
                                          weights='imagenet')
gap = tf.keras.layers.GlobalAveragePooling2D()(net.output)
op = Dense(10, activation=tf.nn.softmax, use_bias=True)(gap)

model = tf.keras.models.Model(inputs=net.input, outputs=op)
model.compile(optimizer="adam",
              loss=tf.keras.losses.CategoricalCrossentropy(),
              metrics=["accuracy"])
his = model.fit(x_train, y_train, epochs=1, batch_size=128)

469/469 [==============================] - 24s 41ms/step - loss: 0.1978 - accuracy: 0.9438


In [10]:
ip = tf.keras.Input(shape=(32,32,3))
net = tf.keras.applications.EfficientNetB0(input_tensor = ip,
                                          include_top=False,
                                          weights='imagenet')
gap = tf.keras.layers.GlobalAveragePooling2D()(net.output)
op = Dense(10, activation=tf.nn.softmax, use_bias=True)(gap)

model = tf.keras.models.Model(inputs=net.input, outputs=op)
model.compile(optimizer="adam",
              loss=tf.keras.losses.CategoricalCrossentropy(),
              metrics=["accuracy"])
his = model.fit(x_train, y_train, epochs=1, batch_size=128)

469/469 [==============================] - 83s 161ms/step - loss: 0.1878 - accuracy: 0.9429


In [11]:
ip = tf.keras.Input(shape=(32,32,3))
net = tf.keras.applications.VGG19(input_tensor = ip,
                                          include_top=False,
                                          weights='imagenet')
gap = tf.keras.layers.GlobalAveragePooling2D()(net.output)
op = Dense(10, activation=tf.nn.softmax, use_bias=True)(gap)

model = tf.keras.models.Model(inputs=net.input, outputs=op)
model.compile(optimizer="adam",
              loss=tf.keras.losses.CategoricalCrossentropy(),
              metrics=["accuracy"])
his = model.fit(x_train, y_train, epochs=1, batch_size=128)

469/469 [==============================] - 142s 299ms/step - loss: 0.8332 - accuracy: 0.6928


In [14]:
ip = tf.keras.Input(shape=(32,32,3))
net = tf.keras.applications.ResNet50V2(input_tensor = ip,
                                          include_top=False,
                                          weights='imagenet')
gap = tf.keras.layers.GlobalAveragePooling2D()(net.output)
op = Dense(10, activation=tf.nn.softmax, use_bias=True)(gap)

model = tf.keras.models.Model(inputs=net.input, outputs=op)
model.compile(optimizer="adam",
              loss=tf.keras.losses.CategoricalCrossentropy(),
              metrics=["accuracy"])
his = model.fit(x_train, y_train, epochs=1, batch_size=128)

469/469 [==============================] - 111s 226ms/step - loss: 0.1756 - accuracy: 0.9531


In [16]:
ip = tf.keras.Input(shape=(32,32,3))
net = tf.keras.applications.MobileNetV3Large(input_tensor = ip,
                                          include_top=False,
                                          weights='imagenet')
gap = tf.keras.layers.GlobalAveragePooling2D()(net.output)
op = Dense(10, activation=tf.nn.softmax, use_bias=True)(gap)

model = tf.keras.models.Model(inputs=net.input, outputs=op)
model.compile(optimizer="adam",
              loss=tf.keras.losses.CategoricalCrossentropy(),
              metrics=["accuracy"])
his = model.fit(x_train, y_train, epochs=1, batch_size=128)

469/469 [==============================] - 23s 38ms/step - loss: 0.2213 - accuracy: 0.9354


In [17]:
ip = tf.keras.Input(shape=(32,32,3))
net = tf.keras.applications.MobileNetV3Small(input_tensor = ip,
                                          include_top=False,
                                          weights='imagenet')
gap = tf.keras.layers.GlobalAveragePooling2D()(net.output)
op = Dense(10, activation=tf.nn.softmax, use_bias=True)(gap)

model = tf.keras.models.Model(inputs=net.input, outputs=op)
model.compile(optimizer="adam",
              loss=tf.keras.losses.CategoricalCrossentropy(),
              metrics=["accuracy"])
his = model.fit(x_train, y_train, epochs=1, batch_size=128)

469/469 [==============================] - 16s 23ms/step - loss: 0.4637 - accuracy: 0.8607


In [18]:
ip = tf.keras.Input(shape=(32,32,3))
net = tf.keras.applications.MobileNet(input_tensor = ip,
                                          include_top=False,
                                          weights='imagenet')
gap = tf.keras.layers.GlobalAveragePooling2D()(net.output)
op = Dense(10, activation=tf.nn.softmax, use_bias=True)(gap)

model = tf.keras.models.Model(inputs=net.input, outputs=op)
model.compile(optimizer="adam",
              loss=tf.keras.losses.CategoricalCrossentropy(),
              metrics=["accuracy"])
his = model.fit(x_train, y_train, epochs=1, batch_size=128)

469/469 [==============================] - 53s 108ms/step - loss: 0.1646 - accuracy: 0.9551


In [19]:
ip = tf.keras.Input(shape=(32,32,3))
net = tf.keras.applications.EfficientNetV2B0(input_tensor = ip,
                                          include_top=False,
                                          weights='imagenet')
gap = tf.keras.layers.GlobalAveragePooling2D()(net.output)
op = Dense(10, activation=tf.nn.softmax, use_bias=True)(gap)

model = tf.keras.models.Model(inputs=net.input, outputs=op)
model.compile(optimizer="adam",
              loss=tf.keras.losses.CategoricalCrossentropy(),
              metrics=["accuracy"])
his = model.fit(x_train, y_train, epochs=1, batch_size=128)

469/469 [==============================] - 70s 131ms/step - loss: 0.1665 - accuracy: 0.9505
